### ISSUE TITLE
Label the page ORF or CRISPR

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/monorepo#18]
Once the URL resolves for broad.io/crispr and broad.io/orf you cannot tell which one you're looking at. So a nice "JUMP ORF dataset" and "JUMP CRISPR dataset" at the top would be nice (feel free to use our image from here if you like: https://jump-cellpainting.broadinstitute.org/)

We should also add a disclaimer that the profiles are being re-processed to improve quality and matching ability (& refer to the version being used? we might not have version numbers instated yet) so to save results and don't be surprised if they change. For this reason perhaps we should mark the page as beta version!

**Comment by AnneCarpenter** [comment]
please :D I keep looking up genes and needing to re-load from the broad.io address to be sure whether I'm looking at ORFs and CRISPRs

**Comment by afermg** [comment]
This is a tricky one! Yet it may be possible. The main challenge is that I am trying to avoid hosting our own version of datasette (most code runs in-browser, the "seed" code that downloads everything is [lite.datasette.io](https://github.com/simonw/datasette-lite), which makes fine-grained edits of the interface very tricky. I'll add technical details for my own reference when I get to tackle this feature. I think it is achievable by providing a metadata file:

- Datasette (base) supports [per-table metadata](https://docs.datasette.io/en/stable/metadata.html#per-database-and-per-table-metadata).
- We can provide metadata to Datasette Lite from [an url](https://github.com/simonw/datasette-lite/tree/ac3da205024872be6b18fc22247adf10cace1a2a?tab=readme-ov-file#loading-metadata).

This assumes that we still use parquet files. We can also combine all tables (e.g., crispr, orf) into a single database but that would entail downloading all of them for any query, which will make the initial waiting times longer. That is a different discussion altogether though. In general our group prefers parquet files.

**Comment by AnneCarpenter** [comment]
Wow, I had no idea the underpinnings here - what you say makes perfect sense why it's not simple and I agree it is much nicer to stick with the out of the box functionality vs self hosting if we can possibly manage it.

**Comment by afermg** [comment]
Added labels on bdeaa96841e177c725bc563452bf4246760ae29a (and updated broad.io/X).  See screenshots on how it looks now.
![image](https://github.com/broadinstitute/monorepo/assets/14353896/6a0417f5-e65e-4e99-8389-6fb1e59c2d28)
![image](https://github.com/broadinstitute/monorepo/assets/14353896/b35c13f5-ae8c-43ee-b4cd-f0d719ce1849)
![image](https://github.com/broadinstitute/monorepo/assets/14353896/ec64667c-5e69-4932-b756-f69b3d36975c)

**Comment by AnneCarpenter** [comment]
Fantastic!!
