### ISSUE TITLE
Relationship to jump-cellpainting/compound-annotator

### ISSUE THREAD

**Issue by shntnu** [broadinstitute/monorepo#22]
@afermg 
How is https://github.com/jump-cellpainting/compound-annotator related to https://github.com/broadinstitute/monorepo/tree/main/libs/jump_compound_annotator? 

If we remove [`StandardizeMolecule.py`](https://github.com/jump-cellpainting/compound-annotator/blob/main/StandardizeMolecule.py) from `jump-cellpainting/compound-annotator`, would the repo be completely superseded by `jump_compound_annotator`? If so, we should pull out `StandardizeMolecule.py` into a new repo and archive `compound-annotator` ASAP.

Here's why I think it is superseded

1. [`drugrep.py`](https://github.com/broadinstitute/monorepo/blob/3ed6107bae6d3743192866f679b6dcd20122f027/libs/jump_compound_annotator/src/jump/drugrep.py) is probably doing what I attempted in [`repurposing-annotations.ipynb`](https://github.com/jump-cellpainting/compound-annotator/blob/main/repurposing-annotations.ipynb) 
2. I am guessing some scripts in `jump_compound_annotator` are pulling from `ChEMBL`, and in that case, it would supersede the process for getting annotations from ChEMBL documented in the [`README`](https://github.com/jump-cellpainting/compound-annotator/blob/main/README.md#chembl-annotations)

---

@johnarevalo – also just making sure that `jump_compound_annotator` is the only code base you are using for generating your annotations, correct?

**Comment by afermg** [comment]
You are right in that this will superseed https://github.com/jump-cellpainting/compound-annotator, namely @johnarevalo's branch containing the resource fetching. I still think there will be work to do to integrate John's approach to fetching all resources and that scripts' decision-making and @srijitseal's SMILES standardisation (which is being integrated on PR #23)

**Comment by afermg** [comment]
I'll close the issue because issues on the monorepo are supposed to be software-based, not project-based :)

**Comment by shntnu** [comment]
> You are right in that this will supersede https://github.com/jump-cellpainting/compound-annotator, namely @johnarevalo's branch containing the resource fetching. 

Ok; I will go ahead and archive that repo now

> I still think there will be work to do to integrate John's approach to fetching all resources and that scripts' decision-making

I didn't understand. Can you elaborate?

**Comment by afermg** [comment]
Ideally, we want to reuse John's code to **fetch**  data from the original sources, and then use Srijit's to process it to get the final names. At the moment they are two independent entities and I am unsure as to where @srijitseal got his raw data from. That's worth having in code somewhere.

**Comment by afermg** [comment]
Yes, but John has to do some processing to merge the tables. By final names I mean the "standardized" SMILES. I just mean to say that while these are two different goals, they should share the same input data.

**Comment by afermg** [comment]
Created issue #24 to get that done.
