### ISSUE TITLE
CRISPR landing page requires a click

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/monorepo#40]
The behavior of /crispr is different from /orf. When you go to broad.io/crispr, you get this view, And you need to click "content" to get to the page you'd expect:

![Screenshot 2024-05-17 at 8 13 00 AM](https://github.com/broadinstitute/monorepo/assets/1213811/2f7b059f-0f96-4cfa-8779-600aef3c0dfe)

**Comment by AnneCarpenter** [comment]
(I know it wasn't the case a while ago, so I wonder if this is a transient thing but it happened yesterday and today both.)

**Comment by afermg** [comment]
I noticed this change, I am unsure as to why it happened. I will try to get it sorted out.

**Comment by afermg** [comment]
This should be fixed now! It was a minor typo when updating the links (I really wish we could automate the broad.io shortlinking step :/)
