### ISSUE TITLE
broad.io/crispr and /orf are failing with datasette error

### ISSUE THREAD

**Issue by AnneCarpenter** [broadinstitute/monorepo#53]
Also happens with a random datasette page Shantanu made, so it's either an issue with datasette.io itself, or something you and he have in common calling it. I caught the blue screen just before it errors out in case it helps knowing which step.

Shantanu's is here https://lite.datasette.io/?parquet=https%3A%2F%2Fraw.githubusercontent.com%2Fshntnu%2Frxrx3%2Frefs%2Fheads%2Fmain%2Fmetadata_rxrx3_trimmed.parquet

<img width="1445" alt="Screenshot 2024-11-15 at 4 09 15 PM" src="https://github.com/user-attachments/assets/0bba056d-42ed-481f-9ac3-e03245c4256d">
<img width="1445" alt="Screenshot 2024-11-15 at 4 09 20 PM" src="https://github.com/user-attachments/assets/246457e9-7559-4da2-8d5b-cf6a975389af">

**Comment by afermg** [comment]
Seems to be working fine for me. It may have had to do with the dependencies issue datasette lite had a couple of weeks ago.
![image](https://github.com/user-attachments/assets/617b0575-ac1c-49b1-b064-ee6ea096045e)
